//
// Generated file, do not edit! Created by opp_msgtool 6.0 from maintain.msg.
//

#ifndef __MAINTAIN_M_H
#define __MAINTAIN_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Maintain;
/**
 * Class generated from <tt>maintain.msg:1</tt> by opp_msgtool.
 * <pre>
 * message Maintain
 * {
 *     int finalDecision;
 *     int sender;
 * }
 * </pre>
 */
class Maintain : public ::omnetpp::cMessage
{
  protected:
    int finalDecision = 0;
    int sender = 0;

  private:
    void copy(const Maintain& other);

  protected:
    bool operator==(const Maintain&) = delete;

  public:
    Maintain(const char *name=nullptr, short kind=0);
    Maintain(const Maintain& other);
    virtual ~Maintain();
    Maintain& operator=(const Maintain& other);
    virtual Maintain *dup() const override {return new Maintain(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getFinalDecision() const;
    virtual void setFinalDecision(int finalDecision);

    virtual int getSender() const;
    virtual void setSender(int sender);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Maintain& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Maintain& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Maintain *fromAnyPtr(any_ptr ptr) { return check_and_cast<Maintain*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MAINTAIN_M_H

