//
// Generated file, do not edit! Created by opp_msgtool 6.0 from sendValue.msg.
//

#ifndef __SENDVALUE_M_H
#define __SENDVALUE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SendValue;
/**
 * Class generated from <tt>sendValue.msg:2</tt> by opp_msgtool.
 * <pre>
 * message SendValue
 * {
 *     int value;
 *     int sender;
 * }
 * </pre>
 */
class SendValue : public ::omnetpp::cMessage
{
  protected:
    int value = 0;
    int sender = 0;

  private:
    void copy(const SendValue& other);

  protected:
    bool operator==(const SendValue&) = delete;

  public:
    SendValue(const char *name=nullptr, short kind=0);
    SendValue(const SendValue& other);
    virtual ~SendValue();
    SendValue& operator=(const SendValue& other);
    virtual SendValue *dup() const override {return new SendValue(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getValue() const;
    virtual void setValue(int value);

    virtual int getSender() const;
    virtual void setSender(int sender);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SendValue& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SendValue& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SendValue *fromAnyPtr(any_ptr ptr) { return check_and_cast<SendValue*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SENDVALUE_M_H

