//
// Generated file, do not edit! Created by opp_msgtool 6.0 from prova.msg.
//

#ifndef __PROVA_M_H
#define __PROVA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Prova;
/**
 * Class generated from <tt>prova.msg:1</tt> by opp_msgtool.
 * <pre>
 * message Prova
 * {
 *     int data[];
 * 
 * 
 * }
 * </pre>
 */
class Prova : public ::omnetpp::cMessage
{
  protected:
    int *data = nullptr;
    size_t data_arraysize = 0;

  private:
    void copy(const Prova& other);

  protected:
    bool operator==(const Prova&) = delete;

  public:
    Prova(const char *name=nullptr, short kind=0);
    Prova(const Prova& other);
    virtual ~Prova();
    Prova& operator=(const Prova& other);
    virtual Prova *dup() const override {return new Prova(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setDataArraySize(size_t size);
    virtual size_t getDataArraySize() const;
    virtual int getData(size_t k) const;
    virtual void setData(size_t k, int data);
    virtual void insertData(size_t k, int data);
    [[deprecated]] void insertData(int data) {appendData(data);}
    virtual void appendData(int data);
    virtual void eraseData(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Prova& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Prova& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Prova *fromAnyPtr(any_ptr ptr) { return check_and_cast<Prova*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PROVA_M_H

